### PR TITLE
Test pre-release for MOM5 with generic tracer WOMBAT

### PR DESCRIPTION
**Pull request by dougiesquire**
**Do not merge**

This PR is to deploy a pre-release with the MOM5 changes required to run with the rewritten (generic tracer) WOMBAT.

### CODE REVIEW

**Comment by dougiesquire** [comment]
!bump major

**Comment by dougiesquire** [comment]
@CodeGat?

**Comment by CodeGat** [comment]
!bump major

**Comment by CodeGat** [comment]
For posterity: we attempted using a short hash `@git.ea4d31`, the full hash `@git.ea4d313d6731fe6621cab26495685a77963f7cdc` and the hash without the @git specifier `@ea4d313d6731fe6621cab26495685a77963f7cdc`. Seems like the repo is not being updated to include that commit, in spack.

**Comment by dougiesquire** [comment]
I'm curious if we know what happened here?

**Comment by CodeGat** [comment]
I'm not certain at the moment...instead of a test commit, can we try a test branch instead?

**Comment by dougiesquire** [comment]
Not sure what the right syntax for a branch is. Also the branch has a `/` in the name which might cause problems

**Comment by CodeGat** [comment]
This pull request will have to be rebased onto the new `main` - did some history rewriting here.

**Comment by harshula** [comment]
Thanks @dougiesquire , We'll look at it.

**Comment by harshula** [comment]
Hi @aidanheerdegen , This looks like the Pre-release namespace clash you were anticipating.

**Comment by harshula** [comment]
https://spack.readthedocs.io/en/latest/module_file_support.html#customize-the-naming-of-modules

**Comment by harshula** [comment]
Hi @dougiesquire , We are planning on changing https://github.com/ACCESS-NRI/build-cd/blob/8600aabc1b1620cfe9b7011a4f4c533aace1d4cd/.github/workflows/ci.yml#L185 to allow `$MODULE_VER` to be null.

**Comment by chrisb13** [comment]
@dougiesquire @aidanheerdegen, @harshula, @CodeGat. Following from the Slack chat and some Friday discussion I missed..

> The following are the _correct_ MOM binaries built by the `pr76-26` deployment:
> 
> ```shell
> $ ls -alh /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-git.2024.08.23_2024.08.23-oi2lpoedckoyp742smul5qcuoxwu2o3g/bin
> total 73M
> drwxr-sr-x+ 2 tm70_ci vk83 4.0K Oct 21 20:48 .
> drwxr-sr-x+ 4 tm70_ci vk83 4.0K Oct 21 20:48 ..
> -rwxr-xr-x+ 1 tm70_ci vk83  73M Oct 21 20:49 fms_ACCESS-OM.x
> -rwxr-xr-x+ 1 tm70_ci vk83 174K Oct 21 20:49 mppnccombine.spack
> ```

@dougiesquire, how do you know it's these ones? Following @anton-seaice's suggestion, I was going to run a test with the exact paths to the four executables but I don't know how to choose which ones are the ones built by `pr76-26`. Doing find in here:
```bash
[cyb561.gadi-login-05: linux-rocky8-x86_64]$ pwd
/g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64
```
Gives many options:
```bash
[1284][cyb561.gadi-login-05: linux-rocky8-x86_64]$ find ./ -iname "*fms_ACCESS*"
./intel-2021.10.0/mom5-git.2023.11.09_2023.11.09-jiaz6eo2n2ovh6nnv6b6v4dg3byspefx/bin/fms_ACCESS-OM-BGC.x
./intel-2021.10.0/mom5-git.dougiesquire_issue388-accessom-gtracer_2024.06.27-git.8-y45ahkw2oxthkp5wefrjsynqwq4ubwy5/bin/fms_ACCESS-OM.x
./intel-2021.10.0/mom5-git.2023.11.09_2023.11.09-ysj247r6owjfwcralshyy4yqpges7n6o/bin/fms_ACCESS-OM.x
./intel-19.0.5.281/mom5-git.development_2024.06.27-git.3-ze3ogc622mubqjzgw7wedpeehdf6fyoj/bin/fms_ACCESS-OM.x
./intel-19.0.5.281/mom5-git.dev_2024.08.14_2024.08.14-4wmrmgtcarc332xbdp34b4dm3ho7gg7c/bin/fms_ACCESS-OM.x
./intel-19.0.5.281/mom5-git.development_2024.06.27-git.3-qb5tdudpdvupxmorqhawlxrjtmbmpsdz/bin/fms_ACCESS-OM.x
./intel-19.0.5.281/mom5-git.2024.08.23_2024.08.23-oi2lpoedckoyp742smul5qcuoxwu2o3g/bin/fms_ACCESS-OM.x
[1285][cyb561.gadi-login-05: linux-rocky8-x86_64]$ find ./ -iname "*yatm*"
./intel-2021.10.0/libaccessom2-git.2023.10.26_2023.10.26-qotmoon5sfw6zp2hnjpntyjjpel7qi45/bin/yatm.exe
./intel-2021.10.0/libaccessom2-git.2023.10.26_2023.10.26-qotmoon5sfw6zp2hnjpntyjjpel7qi45/include/yatm_version_mod.mod
./intel-2021.10.0/libaccessom2-git.2023.10.26_2023.10.26-hsvb52bxolscdz6klzydntoay7yf7nlz/bin/yatm.exe
./intel-2021.10.0/libaccessom2-git.2023.10.26_2023.10.26-hsvb52bxolscdz6klzydntoay7yf7nlz/include/yatm_version_mod.mod
./intel-2021.10.0/libaccessom2-git.2023.10.26_2023.10.26-tlis5urth5tc2snznv6uv2oqlelxwbrr/bin/yatm.exe
./intel-2021.10.0/libaccessom2-git.2023.10.26_2023.10.26-tlis5urth5tc2snznv6uv2oqlelxwbrr/include/yatm_version_mod.mod
./intel-19.0.5.281/libaccessom2-git.2023.10.26_2023.10.26-l6hmyszag4j7dey6j5wuahzy7mnh4nl3/bin/yatm.exe
./intel-19.0.5.281/libaccessom2-git.2023.10.26_2023.10.26-l6hmyszag4j7dey6j5wuahzy7mnh4nl3/include/yatm_version_mod.mod
./intel-19.0.5.281/libaccessom2-git.2023.10.26_2023.10.26-xarvbgn4yf4mxy5hxixm4gfbp7rbzsfh/bin/yatm.exe
./intel-19.0.5.281/libaccessom2-git.2023.10.26_2023.10.26-xarvbgn4yf4mxy5hxixm4gfbp7rbzsfh/include/yatm_version_mod.mod
[1286][cyb561.gadi-login-05: linux-rocky8-x86_64]$ find ./ -iname "*cice_auscom_360x300_24x1_24p.exe*"
./intel-2021.10.0/cice5-git.2023.10.19_2023.10.19-3khrmuxma7p4wifa5av2biukx4iomk2l/bin/cice_auscom_360x300_24x1_24p.exe
./intel-2021.10.0/cice5-git.2023.10.19_2023.10.19-a7nepxaj3durabe7ndhkmyxl4gint4r7/bin/cice_auscom_360x300_24x1_24p.exe
./intel-2021.10.0/cice5-git.2023.10.19_2023.10.19-kwi3fa7zzkrkzjqciusglmud7q4hwcpl/bin/cice_auscom_360x300_24x1_24p.exe
./intel-19.0.5.281/cice5-git.2023.10.19_2023.10.19-4tttbvaxg4afg3hjcrfaah6qngp43e5e/bin/cice_auscom_360x300_24x1_24p.exe
./intel-19.0.5.281/cice5-git.2023.10.19_2023.10.19-epnbkescatwhxi2pvcjlj5eflcaupj3t/bin/cice_auscom_360x300_24x1_24p.exe
[cyb561.gadi-login-05: linux-rocky8-x86_64]$ find ./ -iname "*mppnccombine.spack*"
./intel-2021.10.0/mom5-git.2023.11.09_2023.11.09-jiaz6eo2n2ovh6nnv6b6v4dg3byspefx/bin/mppnccombine.spack
./intel-2021.10.0/mom5-git.dougiesquire_issue388-accessom-gtracer_2024.06.27-git.8-y45ahkw2oxthkp5wefrjsynqwq4ubwy5/bin/mppnccombine.spack
./intel-2021.10.0/mom5-git.2023.11.09_2023.11.09-ysj247r6owjfwcralshyy4yqpges7n6o/bin/mppnccombine.spack
./intel-19.0.5.281/mom5-git.development_2024.06.27-git.3-ze3ogc622mubqjzgw7wedpeehdf6fyoj/bin/mppnccombine.spack
./intel-19.0.5.281/mom5-git.dev_2024.08.14_2024.08.14-4wmrmgtcarc332xbdp34b4dm3ho7gg7c/bin/mppnccombine.spack
./intel-19.0.5.281/mom5-git.development_2024.06.27-git.3-qb5tdudpdvupxmorqhawlxrjtmbmpsdz/bin/mppnccombine.spack
./intel-19.0.5.281/mom5-git.2024.08.23_2024.08.23-oi2lpoedckoyp742smul5qcuoxwu2o3g/bin/mppnccombine.spack
```
Posting here as I thought it would be helpful to have the answer in a public spot for the next naive person. ;)

**Comment by anton-seaice** [comment]
You can check the build log e.g. [here](https://github.com/ACCESS-NRI/ACCESS-OM2/actions/runs/11512177442/job/32046810278#step:8:663) and check via the spack hash

In general, if you have a spack installation of the environment, I think you could find the spack hashes and check them by searching the results of  `spack find --deps`

**Comment by chrisb13** [comment]
Update for [this PR](https://github.com/ACCESS-NRI/ACCESS-OM2/pull/82#issuecomment-2434815952). Now compared [this run](https://github.com/ACCESS-NRI/ACCESS-OM2/pull/82#issuecomment-2406485256) with `pr76-26` as suggested by @dougiesquire [here](https://github.com/ACCESS-NRI/ACCESS-OM2/pull/82#issuecomment-2426237689). Due to [this issue](https://github.com/ACCESS-NRI/build-cd/issues/157#issue-2628281465), full executables in [config.yaml.txt](https://github.com/user-attachments/files/17654575/config.yaml.txt) were used. _TL;DR differences exist but are very small, I think we are ok._

**Details.** md5sums are different..
```bash
[1747][cyb561.gadi-login-02: ocean]$ pwd #Dougie's
/home/561/cyb561/access-om2/1deg_jra55_ryf4_dougie/archive/output000/ocean
[cyb561.gadi-login-02: ocean]$ md5sum oceanbgc-3d-zprod_gross-1-monthly-mean-y_1900.nc
bc09f28137688ba6b62acff00aa2c4b9  oceanbgc-3d-zprod_gross-1-monthly-mean-y_1900.nc
```

```bash
[1742][cyb561.gadi-login-05: ocean]$ pwd #Chris'
/home/561/cyb561/access-om2/1deg_jra55_ryf3_cb/archive/output000/ocean
[cyb561.gadi-login-05: ocean]$ md5sum oceanbgc-3d-zprod_gross-1-monthly-mean-y_1900.nc
8b50e69cbc72d9f01ee0612b96b7f162  oceanbgc-3d-zprod_gross-1-monthly-mean-y_1900.nc
```

Actual fields have very small differences.. Visualising the ncdiff (`[cyb561.gadi-login-02: ocean]$ ncdiff /home/561/cyb561/access-om2/1deg_jra55_ryf4_dougie/archive/output000/ocean/oceanbgc-3d-zprod_gross-1-monthly-mean-y_1900.nc /home/561/cyb561/access-om2/1deg_jra55_ryf3_cb/archive/output000/ocean/oceanbgc-3d-zprod_gross-1-monthly-mean-y_1900.nc oceanbgc-3d-zprod_gross-1-monthly-mean-y_1900_diffd.nc`) gives:
image

**Comment by CodeGat** [comment]
Hey @dougiesquire, due to:
* [The update to Prerelease versioning](https://github.com/ACCESS-NRI/build-cd/pull/167) (in which we now use number of deployments rather than number of commits, which allows rebasing), and
* [The update to Projections in the `spack.yaml`](https://github.com/ACCESS-NRI/ACCESS-OM2/issues/84) 

Some of the `spack` environment names may clash for future deployments in this PR. If possible, can we move this to a new PR, and close this one? Happy to help out if needed.

**Comment by dougiesquire** [comment]
Thanks @CodeGat. I think we can probably just close this PR, but I'll wait for @chrisb13 to confirm that he doesn't need the prerelease deployments anymore.

**Comment by harshula** [comment]
Hi @dougiesquire & @chrisb13, I'll close this PR and reopen another using the same branch. I'd like to keep a Pre-Release of a non-componentized generic tracers Spack build as a reference.

**Pull request closed without merging**
