### PR TITLE
Add restart reproducibility variant for mom5

### LINKED ISSUE #53: Add +restart_repro variant
Restart reproducibility variant has been added to the MOM5 SPD:

https://github.com/ACCESS-NRI/spack-packages/pull/67

To address [lack of restart reproducibility](https://github.com/ACCESS-NRI/access-om2-configs/issues/11).

This variant should be added to ACCESS-OM2 via a PR. 

This will allow for this fix to be tested, and for performance testing to be done on a wider range of configurations.

Once tests pass and performance testing has been signed off this can be merged.

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Add +restart_repro variant for mom5

Closes #53

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
I **think** I've used the right syntax for this, but happy to be told otherwise. 

The other option is that we add this as the default variant for the [`access-om2` SPD](https://github.com/ACCESS-NRI/spack-packages/blob/main/packages/access-om2/package.py). Don't mind either way, but not sure what that would entail.

**Comment by aidanheerdegen** [comment]
!bump major

**Comment by aidanheerdegen** [comment]
Bumped the major version because bitwise restart reproducibility represents a significant change in functionality.

**Comment by aidanheerdegen** [comment]
We're going to need to push a new `spack-packages` version to pick up the updated `mom5` SPD right @CodeGat?

https://github.com/ACCESS-NRI/spack-packages/commit/203abecccd8426130b354c24b8b54d8604387dcd

**Comment by CodeGat** [comment]
The Ci is failing because it's not comparing the versions correctly. Haven't dealt with the case as seen here: https://github.com/ACCESS-NRI/ACCESS-OM2/pull/54/files#diff-e8582e74fa156f4e5729a850e52b24f2fde2d815c2c9c360f88c4cf90db851abR13
This will require an update to the CI to fix - where is that syntax defined, @aidanheerdegen?

**Comment by aidanheerdegen** [comment]
No longer required as `+restart_repro` was made default for `mom5`

https://github.com/ACCESS-NRI/spack-packages/pull/83

**Pull request closed without merging**
