### PR TITLE
Require parallelio 2.5.2

### PR DESCRIPTION
**Pull request by harshula**
See https://github.com/ACCESS-NRI/ACCESS-OM2/issues/30

### CODE REVIEW

**Review by CodeGat — APPROVED** [review]
Looks good to me.
Although not relevant for this particular deployment, note the `config/version.json` file. It contains the versions of `spack-packages` and `spack-config` that will be used to deploy `access-om2`. Right now they are the latest, but in future this will change.

**Comment by CodeGat** [comment]
Something also worth noting is that I had to explicitly comment about the `config/versions.json` thing. This should be a CI check or warning, if a PR hasn't touched this. Alternatively, a comment could be made, like "This `spack.yaml` will be used to deploy `access-om2` with `spack-config` vX and `spack-packages` vY"

**Review by aidanheerdegen — APPROVED** [review]
LGTM2

**Comment by harshula** [comment]
The following has to be done to deploy these changes: https://github.com/ACCESS-NRI/ACCESS-OM2/issues/33

**Pull request merged**
