### PR TITLE
Depend on openmpi instead of nci-openmpi and add restart reproducibility

### PR DESCRIPTION
**Pull request by harshula**
* Requires: https://github.com/ACCESS-NRI/spack-packages/pull/66
* Requires: https://github.com/ACCESS-NRI/spack-config/pull/26

### CODE REVIEW

**Comment by harshula** [comment]
This change was triggered by https://github.com/ACCESS-NRI/spack-packages/issues/61 .

**Review by CodeGat — CHANGES_REQUESTED** [review]
We'll need to update the version before merging it - if you rebase onto main it should help out telling what needs to be done.

**Comment by aidanheerdegen** [comment]
!bump minor

**Comment by aidanheerdegen** [comment]
Pre-release deployment is reporting

> /bin/bash: line 5: /g/data/vk83/prerelease/apps/spack/0.20/spack-config/spack-enable.bash: No such file or directory

Despite this change

https://github.com/ACCESS-NRI/build-cd/pull/31/files

Seems that on `gadi` it is still called `spack-start.sh`

```
$ ls /g/data/vk83/prerelease/apps/spack/0.20/spack-config/
LICENSE  README.md  spack-start.bash  tools  v0.20
```

**Comment by CodeGat** [comment]
Might need to check the version tagged in `config/versions.json` in the morning - is it spack-enable.bash in that tag? Or spack-start?

**Comment by CodeGat** [comment]
!bump major

**Review by aidanheerdegen — APPROVED** [review]
LGTM

**Comment by aidanheerdegen** [comment]
We shouldn't merge until we have done some performance testing, confirming the impact is minimal

**Comment by CodeGat** [comment]
Good point @aidanheerdegen - I've requested changes so it shouldn't be able to merge

**Comment by aidanheerdegen** [comment]
Seems the pre-release build is still using `nci-openmpi`
```
$ grep openmpi /g/data/vk83/prerelease/apps/spack/0.20/spack/var/spack/environments/access-om2-2024_03_0-4/spack.lock                                 
          "name": "nci-openmpi",
          "name": "nci-openmpi",
      "name": "nci-openmpi",
        "path": "/apps/openmpi/4.0.2",
          "openmpi/4.0.2"
          "name": "nci-openmpi",
          "name": "nci-openmpi",
          "name": "nci-openmpi",
          "name": "nci-openmpi",
          "name": "nci-openmpi",
```

**Comment by CodeGat** [comment]
What does this mean, exactly...?

**Comment by CodeGat** [comment]
@harshula

**Comment by CodeGat** [comment]
@harshula The openmpi thing was fixed - we hadn't tagged the `nci-openmpi`->`openmpi` fix in `spack-config`.

**Comment by harshula** [comment]
Hi @CodeGat , Is there anything else we need to do?

**Comment by CodeGat** [comment]
I assume some kind of performance testing of some kind before proper deployment

**Review by CodeGat — APPROVED** [review]

**Review by aidanheerdegen — APPROVED** [review]
Looks good. Performance checks suggest no issue with model slowdown.

https://github.com/ACCESS-NRI/access-om2-configs/issues/35

**Pull request merged**
